Controllers/EstablishmentController.cs
using Delivery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Delivery.Controllers;

public class EstablishmentController : Controller
{
    private readonly DeliveryContext _context;
    private readonly IWebHostEnvironment _hostEnvironment;

    public EstablishmentController(DeliveryContext context, IWebHostEnvironment hostEnvironment)
    {
        _context = context;
        _hostEnvironment = hostEnvironment;
    }
    
    public async Task<IActionResult> Index()
    {
        var establishments = await _context.Establishments.ToListAsync();
        return View(establishments);
    }

    public async Task<IActionResult> Details(int id)
    {
        var establishment = await _context.Establishments.Include(e => e.Dishes)
                .FirstOrDefaultAsync(e => e.Id == id);
        if (establishment == null)
        {
                return NotFound();
        }
        return View(establishment);
    }

    [Authorize(Roles = "admin, manager")]
    public IActionResult Create()
    {
        return View();
    }

    [Authorize(Roles = "admin, manager")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Establishment establishment)
    {
        if (establishment.ImageFile == null)
        {
            ModelState.AddModelError("ImageFile", "Картинка обязательна для скачивания");
            return View(establishment);
        }

        if (await _context.Establishments.FirstOrDefaultAsync(e => e.Name == establishment.Name) != null)
        {
            ModelState.AddModelError("Name", "Заведение с таким именем уже существует");
            return View(establishment);
        }
        if (ModelState.IsValid)
        {
            if (establishment.ImageFile != null && establishment.ImageFile.Length > 0)
            {
                
                var uploadPath = Path.Combine(_hostEnvironment.WebRootPath, "images");
                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                }
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(establishment.ImageFile.FileName);
                var fullPath = Path.Combine(uploadPath, fileName);
            
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    await establishment.ImageFile.CopyToAsync(fileStream);
                }
            
                establishment.Image = "/images/" + fileName;
            }
            _context.Add(establishment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(establishment);
    }

    [Authorize(Roles = "admin, manager")]
    public async Task<IActionResult> Edit(int id)
    {
        var establishment = await _context.Establishments.Include(e => e.Dishes)
            .FirstOrDefaultAsync(e => e.Id == id);
        if (establishment == null)
        {
            return NotFound();
        }
        return View(establishment);
    }

    [Authorize(Roles = "admin, manager")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Establishment establishment)
    {
        if (await _context.Establishments.FirstOrDefaultAsync(e => e.Name == establishment.Name && e.Id != establishment.Id) != null)
        {
            establishment.Dishes = await _context.Dishes.Where(d => d.EstablishmentId == establishment.Id).ToListAsync();

            ModelState.AddModelError("Name", "Заведение с таким именем уже существует");
            return View(establishment);
        }
        if (ModelState.IsValid)
        {
            if (establishment.ImageFile != null && establishment.ImageFile.Length > 0)
            {
                
                var uploadPath = Path.Combine(_hostEnvironment.WebRootPath, "images");
                if (!Directory.Exists(uploadPath))
                { 
                    Directory.CreateDirectory(uploadPath);
                }
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(establishment.ImageFile.FileName);
                var fullPath = Path.Combine(uploadPath, fileName);
            
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    await establishment.ImageFile.CopyToAsync(fileStream);
                }
            
                establishment.Image = "/images/" + fileName;
            }
            _context.Update(establishment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(establishment);
    }

    [Authorize(Roles = "admin, manager")]
    public async Task<IActionResult> Delete(int id)
    {
        var establishment = await _context.Establishments.FindAsync(id);
        if (establishment != null)
        {
            _context.Establishments.Remove(establishment);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction(nameof(Index));
    }

    [Authorize(Roles = "admin, manager")]
    public async Task<IActionResult> CreateDish(int establishmentId)
    {
        Establishment? establishment = await _context.Establishments.FirstOrDefaultAsync(e => e.Id == establishmentId);
        if (establishment != null)
        {
            return View(new Dish() {Establishment = establishment});
        }

        return NotFound();
    }

    [Authorize(Roles = "admin, manager")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateDish(Dish dish)
    {
        if (ModelState.IsValid)
        {
            _context.Add(dish);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = dish.EstablishmentId });
        }
        return View(dish);
    }

    [Authorize(Roles = "admin, manager")]
    public async Task<IActionResult> EditDish(int id)
    {
        var dish = await _context.Dishes.FindAsync(id);
        if (dish == null)
        {
            return NotFound();
        }
        return View(dish);
    }

    [Authorize(Roles = "admin, manager")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditDish(Dish dish)
    {
        if (ModelState.IsValid)
        { 
            _context.Update(dish); 
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = dish.EstablishmentId });
        }
        return View(dish);
    }

    [Authorize(Roles = "admin, manager")]
    public async Task<IActionResult> DeleteDish(int id)
    {
        var dish = await _context.Dishes.FindAsync(id);
        if (dish != null)
        {
            _context.Dishes.Remove(dish);
            await _context.SaveChangesAsync();
        }
        return RedirectToAction("Details", new { id = dish.EstablishmentId });
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Delivery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Delivery.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Delivery</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                        </li>
                        <li class="nav-item">
                            <span class="nav-link text-dark">Привет, @User.Identity.Name!</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Establishment" asp-action="Index">Все заведения</a>
                        </li>
                        if (User.IsInRole("admin") || User.IsInRole("manager"))
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Establishment" asp-action="Create">Создать заведение</a>
                            </li>
                        }
                        if (User.IsInRole("admin"))
                        {
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Список пользователей</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Создать нового пользователя</a>

                        }
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Delivery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>